### ISSUE TITLE
Написать оформленное ТЗ

### ISSUE THREAD

**Issue by Grolider** [Grolider/DataBase_CourseWork#2]

**Comment by Grolider** [comment]
**Техническое задание**
1.1 ОБЩИЕ ПОЛОЖЕНИЯ
1.1.1	Полное наименование системы
Система для ведения библиотечного учёта

1.1.2	Перечень документов, на основании которых создается система
Система создается на основании данного технического задания. Иных документов по созданию системы для ведения библиотечного учёта не предусмотрено.

1.1.3	Плановые сроки начала и окончания работы по созданию системы
Систему необходимо разработать в период с 01.09.2022 по 01.12.2022 и приступить к ее внедрению и сопровождению. 

1.1.4	Порядок оформления и предъявления заказчику результатов работ по созданию системы
Организованы еженедельные консультации с заказчиком для демонстрации промежуточных результатов работы, обсуждения предметной области, выявления и решения текущих проблем.

1.2 НАЗНАЧЕНИЕ И ЦЕЛИ СОЗДАНИЯ СИСТЕМЫ
1.2.1	Назначение системы 
Назначением системы является автоматизация организационной работы сети библиотек с помощью приложения с использованием базы данных.

1.2.2	Цели создания системы
Целью создания данного программного продукта является централизация управления сетью из нескольких библиотек. Система создаётся для ведения библиотечного учёта и контроля деятельности работников библиотеки.

1.3 ХАРАКТЕРИСТИКА ОБЪЕКТА АВТОМАТИЗАЦИИ
Объектом автоматизации является рабочие процессы библиотеки и совокупность процессов информационного взаимодействия между разными библиотеками одной сети. Автоматизированию подлежит процесс поступления новых книг, процесс сдачи книг, процесс выдачи книг читателям, процесс записи новых читателей, процесс уведомления библиотек внутри одной сети.

1.4 ТРЕБОВАНИЯ К СИСТЕМЕ
1.4.1	Требования к структуре и функционированию системы
Система должна содержать следующий перечень подсистем:
•	Подсистему администрирования сети библиотек;
•	Подсистему рабочих процессов библиотеки;
•	Единый реестр литературы.
Функционал системы должен содержать:
•	Оформление новой библиотеки;
•	Авторизация пользователей (сотрудников);
•	Поиск литературы;
•	Хранение данных пользователей (сотрудников);
•	Хранение данных читателей.

1.4.2	Требования к надежности
	  Система должна обеспечивать корректную обработку исключительных ситуаций, вызванных, например, вводом неверных пользовательских данных или неоднозначной информации в базу данных. 

1.5 СОСТАВ И СОДЕРЖАНИЕ РАБОТ ПО СОЗДАНИЮ (РАЗВИТИЮ) СИСТЕМЫ
1. Создание прототипа интерфейса. Экспертиза: согласование прототипа с заказчиком. (Срок 4 неделя)
2. Создание концептуальной модели программы. Экспертиза: согласование прототипа с заказчиком. (Срок 7 неделя)
3. Разработка физической и логической схемы программы. Экспертиза: демонстрация проделанной работы заказчику. (Срок 7 неделя)
4. Разработка макета программы. Экспертиза: демонстрация проделанной работы заказчику. (Срок 10 неделя)
5. Отладка и устранение ошибок программы. Экспертиза: демонстрация проделанной работы заказчику. (Срок 14 неделя)

1.6. ПОРЯДОК КОНТРОЛЯ И ПРИЕМКИ СИСТЕМЫ
1.6.1	Виды, состав, объем и методы испытаний системы
Система разрабатывается с применением модульного тестирования. При добавлении нового функционала предыдущие тесты должны сохранять работоспособность. При реализации любой из подсистем результат работы демонстрируется заказчику на тестовых данных.  

1.6.2	Общие требования к приемке работ по стадиям
После демонстрации работоспособности приложения на каждой стадии происходит согласование текущего функционала, после чего разработка переходит на следующую стадию.  

1.6.3	Статус приемочной комиссии
Приемка работы осуществляется комиссией. Состав комиссии утверждается заведующим кафедрой. 

1.8 ТРЕБОВАНИЯ К ДОКУМЕНТИРОВАНИЮ
Требуется предоставить:
1.	Техническое задание в соответствии с ГОСТ 34.602-89
2.	Расчетно-пояснительную записку, включающую исследовательскую часть, проектно-конструкторскую часть и проектно-технологическую часть. Расчетно-пояснительная записка выполняется с учетом требований, предусмотренных ГОСТ 7.32-2001 и 2.105-95.

**Comment by wldmr-key** [comment]
норм, берем

**Comment by wldmr-key** [comment]
класс. Для технического задания - супер
