### ISSUE TITLE
Написать (предварительное) описание предметной области и требований к системе

### ISSUE THREAD

**Issue by Grolider** [Grolider/DataBase_CourseWork#3]

**Comment by Grolider** [comment]
Сеть библиотек с общей базой данных образует библиотечный фонд. Под общей базой данных понимается совместные списки абонементов (зарегистрированных читателей), литературы и сотрудников. Каждый читатель, будучи зарегистрированным в одной из библиотек, имеет доступ ко всему библиотечному фонду.

О каждом читателе заносятся следующие сведения:
·	ФИО,
·	номер паспорта,
·	адрес,
·	телефон.
Каждому читателю присваивается номер читательского билета. Кроме того, учитываются сведения о наличии у читателя штрафов.

В каждую библиотеку приходит много книг из различных издательств. Каждая книга, хранящаяся в библиотеке, имеет следующие параметры:
·	название книги;
·	уникальный шифр (ISBN);
·	библиотечно-библиографическая классификация (ББК);
·	автор;
·	издательство;
·	место издания (город);
·	год издания;
·	количество страниц.

Система для ведения библиотечного также хранит в себе данные сотрудников (они же пользователи).

Пользователь это зарегистрированный работник библиотеки. Данные пользователя включают в себя:
·	ID (уникальный номер сотрудника)
·	ФИО,
·	номер паспорта,
·	номер телефона,
·	номер библиотеки (место работы),
·	является администратором или нет.
·	статус аккаунта.

Статус аккаунта определяет заблокирован ли пользователь или нет. Заблокированный пользователь не имеет доступа к системе.

Пользователи без прав администратора — это обычные сотрудники, выполняющие основные функции библиотекаря. Они работают с книгами и читателями, им необходимо иметь доступ к Базе Данных книг и абонементов (зарегистрированных читателей). 

Пользователи с правами администратора работают с кадрами библиотеки, в их обязанности, кроме обычных функций сотрудников, входит регистрация аккаунтов новых пользователей (обычных сотрудников) и блокировка аккаунта пользователя в случае необходимости. Также могут дать права администратора уже существующему аккаунту пользователя без них.

**Comment by wldmr-key** [comment]
Экземпляр книги - есть такая сущность. В библиотеку пришли три экземпляра книги "Три поросенка". Библиотека делает между ними разницу? Состояние экземпляра книги имеет значение. Читатель вернул книгу "Три поросенка" с разорванной страницей. такое бывает?

**Comment by wldmr-key** [comment]
что такое штраф?

**Comment by Grolider** [comment]
(Дубль 2)
Сеть библиотек с общей базой данных образует библиотечный фонд. Под общей базой данных понимается совместные списки абонементов (зарегистрированных читателей), литературы и сотрудников.

Каждый читатель, будучи зарегистрированным в одной из библиотек, имеет доступ ко всему библиотечному фонду. Каждому читателю присваивается номер читательского билета. Кроме того, учитываются сведения о наличии у читателя штрафов. 

Штраф – это некая сумма, которую читатель должен возместить библиотеке за невыполнение таких обязательств как своевременный возврат книги и/или бережное пользование книгой. Библиотеки отказывают в оказании услуг читателям с непогашенными штрафами.

В каждую библиотеку приходит много книг из различных издательств, причём каждая книга может быть представлена в нескольких экземплярах (каждая книга имеет свой инвентарный номер).

Таким образом система должна содержать сведения о читателях, книгах и пользователях (сотрудниках) и хранить их в соответствующих базах данных.

О каждом читателе заносятся следующие сведения:
·	ФИО,
·	номер паспорта,
·	адрес,
·	телефон.

Каждая книга, хранящаяся в библиотеке, имеет следующие параметры:
·	инвентарный номер (уникальный номер каждого экземпляра)
·	название книги;
·	уникальный шифр (ISBN);
·	библиотечно-библиографическая классификация (ББК);
·	автор;
·	издательство;
·	место издания (город);
·	год издания;
·	количество страниц.

Система для ведения библиотечного также хранит в себе данные сотрудников (они же пользователи).
Пользователь это зарегистрированный работник библиотеки. Данные пользователя включают в себя:
·	ID (уникальный номер сотрудника)
·	ФИО,
·	номер паспорта,
·	номер телефона,
·	номер библиотеки (место работы),
·	является администратором или нет.
·	статус аккаунта.

Статус аккаунта определяет заблокирован ли пользователь или нет. Заблокированный пользователь не имеет доступа к системе.

Пользователи без прав администратора — это обычные сотрудники, выполняющие основные функции библиотекаря. Они работают с книгами и читателями, им необходимо иметь доступ к Базе Данных книг и абонементов (зарегистрированных читателей). 

Пользователи с правами администратора работают с кадрами библиотеки, в их обязанности, кроме обычных функций сотрудников, входит регистрация аккаунтов новых пользователей (обычных сотрудников) и блокировка аккаунта пользователя в случае необходимости. Также могут дать права администратора уже существующему аккаунту пользователя без них.

**Comment by wldmr-key** [comment]
супер
